[package]
name = "wadup_module_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wadup_bindings = { path = "../wadup_bindings_rust" }
anyhow = "1.0.94"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"